### ISSUE TITLE
[BE] Financial Statements Feature

### ISSUE THREAD

**Issue by chaaals** [chaaals/se-financial-reporting#10]
## Description
Implement basic crud operations for FS feature.

## Tasks
- [x] List Financial Statements based on report type `/financial-statements`
- [x] Support filtering on listing Financial Statements `/financial-statements?type={ fs_type }`
Additional context: the reason for this type of URL is because of this dropdown in our sidebar
![image](https://github.com/chaaals/se-financial-reporting/assets/70326902/c409b24f-8bf3-4a8b-93f9-affe8b980ee8)
- [x] Preview Financial Statement `/financial-statements/{ fs_id }`
- [x] Delete Financial Statement
- [ ] Export Financial Statement
