### ISSUE TITLE
[BE] Trial Balance API

### ISSUE THREAD

**Issue by chaaals** [chaaals/se-financial-reporting#3]
## Description
Create an API for Trial Balance feature

## Tasks
- [ ] GET `/api/trial-balances`
- [ ] POST `/api/trial-balances`
- [ ] GET `/api/trial-balances/:id`
- [ ] PATCH `/api/trial-balances/:id`
- [ ] DELETE `/api/trial-balances/:id`
