### ISSUE TITLE
TB Preview clean up and report sending to OVPF via email

### ISSUE THREAD

**Issue by chaaals** [chaaals/se-financial-reporting#63]
## Description
TB Preview needs clean up and polishing and approved reports can be sent to the email of OVPF.

## Specs
- Upon balancing, remove `Rebalance` button
- Show debit and credit grand totals
- When a report is approved the user should be able to send the report to OVPF via email

## Tasks
- [x] Remove rebalance button when the TB is balanced
- [x] Add `debit_grand_totals` and `credit_grand_totals` to TB preview
- [x] Add a CTA button to send the report to email
- [ ] Utilize all totals data than manual computation
