### ISSUE TITLE
Activity Logging

### ISSUE THREAD

**Issue by chaaals** [chaaals/se-financial-reporting#84]
## Description
Add activity logging to the different features of the module.

## Tasks
- [x] Add activity logging to TB Features
- [x] Add activity logging to FS Features
- [x] Add activity logging to Notes feature
- [x] Add log names
